services:
  web-profile-staging:
    restart: always
    build: .
    image: ghcr.io/ianfebi01/web-profile:staging
    container_name: web-profile-staging
    # ports:
    #   - 3001:3000
    networks:
      - proxy
    env_file:
      - .env.staging
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
networks:
  proxy:
    external: true
