/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    tags: Tag;
    skills: Skill;
    projects: Project;
    articles: Article;
    pages: Page;
    experiences: Experience;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'id') | ('en' | 'id')[];
  globals: {
    site: Site;
    profile: Profile;
    'home-page': HomePage;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    profile: ProfileSelect<false> | ProfileSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'en' | 'id';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Cloudinary Media Information
   */
  cloudinary?: {
    /**
     * Cloudinary Public ID (used for transformations)
     */
    public_id?: string | null;
    /**
     * Type of the resource (image, video, raw)
     */
    resource_type?: string | null;
    /**
     * File format
     */
    format?: string | null;
    /**
     * Secure delivery URL
     */
    secure_url?: string | null;
    /**
     * File size in bytes
     */
    bytes?: number | null;
    /**
     * Creation timestamp
     */
    created_at?: string | null;
    /**
     * Current version number
     */
    version?: string | null;
    /**
     * Unique version identifier
     */
    version_id?: string | null;
    /**
     * Width in pixels
     */
    width?: number | null;
    /**
     * Height in pixels
     */
    height?: number | null;
    /**
     * Duration in seconds (for videos)
     */
    duration?: number | null;
    /**
     * Number of pages (for PDFs)
     */
    pages?: number | null;
    /**
     * Which page of the PDF to use for thumbnails (changes will apply after saving)
     */
    selected_page?: number | null;
    /**
     * URL for the thumbnail image (automatically generated for PDFs)
     */
    thumbnail_url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  name: string;
  description?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  description?: string | null;
  content?: string | null;
  thumbnail?: (string | null) | Media;
  gallery?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  url?: string | null;
  skills?: (string | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  slug: string;
  introText?: string | null;
  content?: string | null;
  heroImage?: (string | null) | Media;
  tags?: (string | Tag)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  banner?: (ProfileBannerBlock | BannerStandardBlock)[] | null;
  blocks?:
    | (
        | BodyCopyBlock
        | TextLeftImageRightBlock
        | SimpleCardsBlock
        | SmallBannerBlock
        | DividerBlock
        | AccordianBlock
        | QuoteBlock
        | FeaturedPortofoliosBlock
        | FeaturedExperiencesBlock
        | IconTextsBlock
        | ArticleSearchBlock
        | PortofolioSearchBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProfileBannerBlock".
 */
export interface ProfileBannerBlock {
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner-components.profile-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerStandardBlock".
 */
export interface BannerStandardBlock {
  heading?: string | null;
  description?: string | null;
  background?: (string | null) | Media;
  buttons?:
    | {
        name?: string | null;
        url?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary' | 'transparent') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner-components.banner-standard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BodyCopyBlock".
 */
export interface BodyCopyBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.body-copy';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextLeftImageRightBlock".
 */
export interface TextLeftImageRightBlock {
  image: string | Media;
  fullWidthBgImage?: boolean | null;
  reverse?: boolean | null;
  fullWidth: boolean;
  bodyCopy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  biggerColumn?: ('image' | 'content') | null;
  scaling?: ('contain' | 'cover') | null;
  buttons?:
    | {
        name?: string | null;
        url?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary' | 'transparent') | null;
        id?: string | null;
      }[]
    | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.text-left-image-right';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleCardsBlock".
 */
export interface SimpleCardsBlock {
  title?: string | null;
  cards?:
    | {
        title?: string | null;
        description?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.simple-cards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SmallBannerBlock".
 */
export interface SmallBannerBlock {
  backgroundImage?: (string | null) | Media;
  buttons?:
    | {
        name?: string | null;
        url?: string | null;
        newTab?: boolean | null;
        style?: ('primary' | 'secondary' | 'transparent') | null;
        id?: string | null;
      }[]
    | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.small-banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  title?: string | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.divider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordianBlock".
 */
export interface AccordianBlock {
  items?:
    | {
        heading: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.accordian';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock".
 */
export interface QuoteBlock {
  quote: string;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.quote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPortofoliosBlock".
 */
export interface FeaturedPortofoliosBlock {
  title?: string | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.featured-portofolios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedExperiencesBlock".
 */
export interface FeaturedExperiencesBlock {
  title?: string | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.featured-experiences';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconTextsBlock".
 */
export interface IconTextsBlock {
  icons: {
    image?: (string | null) | Media;
    bodyCopy?: string | null;
    link?: string | null;
    linkNewTab?: boolean | null;
    id?: string | null;
  }[];
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.icon-texts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleSearchBlock".
 */
export interface ArticleSearchBlock {
  title?: string | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.article-search';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortofolioSearchBlock".
 */
export interface PortofolioSearchBlock {
  title?: string | null;
  sectionSettings?: {
    bgColour?: ('dark' | 'dark-secondary' | 'orange' | 'green' | 'white') | null;
    heading?: string | null;
    description?: string | null;
    centreText?: boolean | null;
    largeHeading?: boolean | null;
    textDropShadow?: boolean | null;
    paddingTop?: ('pt-0' | 'pt-2' | 'pt-4' | 'pt-6' | 'pt-8' | 'pt-10' | 'pt-12' | 'pt-16' | 'pt-20' | 'pt-24') | null;
    paddingBottom?:
      | ('pb-0' | 'pb-2' | 'pb-4' | 'pb-6' | 'pb-8' | 'pb-10' | 'pb-12' | 'pb-16' | 'pb-20' | 'pb-24')
      | null;
    marginTop?: ('mt-0' | 'mt-2' | 'mt-4' | 'mt-6' | 'mt-8' | 'mt-10' | 'mt-12' | 'mt-16' | 'mt-20' | 'mt-24') | null;
    marginBottom?:
      | ('mb-0' | 'mb-2' | 'mb-4' | 'mb-6' | 'mb-8' | 'mb-10' | 'mb-12' | 'mb-16' | 'mb-20' | 'mb-24')
      | null;
    /**
     * Optional HTML ID for anchor links
     */
    htmlId?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'content-components.portofolio-search';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  companyName: string;
  role: string;
  startDate: string;
  endDate?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary?:
    | T
    | {
        public_id?: T;
        resource_type?: T;
        format?: T;
        secure_url?: T;
        bytes?: T;
        created_at?: T;
        version?: T;
        version_id?: T;
        width?: T;
        height?: T;
        duration?: T;
        pages?: T;
        selected_page?: T;
        thumbnail_url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  thumbnail?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  url?: T;
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  introText?: T;
  content?: T;
  heroImage?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  banner?:
    | T
    | {
        'banner-components.profile-banner'?: T | ProfileBannerBlockSelect<T>;
        'banner-components.banner-standard'?: T | BannerStandardBlockSelect<T>;
      };
  blocks?:
    | T
    | {
        'content-components.body-copy'?: T | BodyCopyBlockSelect<T>;
        'content-components.text-left-image-right'?: T | TextLeftImageRightBlockSelect<T>;
        'content-components.simple-cards'?: T | SimpleCardsBlockSelect<T>;
        'content-components.small-banner'?: T | SmallBannerBlockSelect<T>;
        'content-components.divider'?: T | DividerBlockSelect<T>;
        'content-components.accordian'?: T | AccordianBlockSelect<T>;
        'content-components.quote'?: T | QuoteBlockSelect<T>;
        'content-components.featured-portofolios'?: T | FeaturedPortofoliosBlockSelect<T>;
        'content-components.featured-experiences'?: T | FeaturedExperiencesBlockSelect<T>;
        'content-components.icon-texts'?: T | IconTextsBlockSelect<T>;
        'content-components.article-search'?: T | ArticleSearchBlockSelect<T>;
        'content-components.portofolio-search'?: T | PortofolioSearchBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProfileBannerBlock_select".
 */
export interface ProfileBannerBlockSelect<T extends boolean = true> {
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerStandardBlock_select".
 */
export interface BannerStandardBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  background?: T;
  buttons?:
    | T
    | {
        name?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BodyCopyBlock_select".
 */
export interface BodyCopyBlockSelect<T extends boolean = true> {
  content?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextLeftImageRightBlock_select".
 */
export interface TextLeftImageRightBlockSelect<T extends boolean = true> {
  image?: T;
  fullWidthBgImage?: T;
  reverse?: T;
  fullWidth?: T;
  bodyCopy?: T;
  biggerColumn?: T;
  scaling?: T;
  buttons?:
    | T
    | {
        name?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleCardsBlock_select".
 */
export interface SimpleCardsBlockSelect<T extends boolean = true> {
  title?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SmallBannerBlock_select".
 */
export interface SmallBannerBlockSelect<T extends boolean = true> {
  backgroundImage?: T;
  buttons?:
    | T
    | {
        name?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  title?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordianBlock_select".
 */
export interface AccordianBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        heading?: T;
        content?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "QuoteBlock_select".
 */
export interface QuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedPortofoliosBlock_select".
 */
export interface FeaturedPortofoliosBlockSelect<T extends boolean = true> {
  title?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedExperiencesBlock_select".
 */
export interface FeaturedExperiencesBlockSelect<T extends boolean = true> {
  title?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconTextsBlock_select".
 */
export interface IconTextsBlockSelect<T extends boolean = true> {
  icons?:
    | T
    | {
        image?: T;
        bodyCopy?: T;
        link?: T;
        linkNewTab?: T;
        id?: T;
      };
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleSearchBlock_select".
 */
export interface ArticleSearchBlockSelect<T extends boolean = true> {
  title?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PortofolioSearchBlock_select".
 */
export interface PortofolioSearchBlockSelect<T extends boolean = true> {
  title?: T;
  sectionSettings?:
    | T
    | {
        bgColour?: T;
        heading?: T;
        description?: T;
        centreText?: T;
        largeHeading?: T;
        textDropShadow?: T;
        paddingTop?: T;
        paddingBottom?: T;
        marginTop?: T;
        marginBottom?: T;
        htmlId?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  companyName?: T;
  role?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: string;
  name: string;
  description?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  socialPlatformLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: string;
  name: string;
  bio?: string | null;
  bannerImage: string | Media;
  avatar: string | Media;
  socialPlatformLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  title: string;
  /**
   * Select the Page document to render as the homepage.
   */
  page: string | Page;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  favicon?: T;
  socialPlatformLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  bannerImage?: T;
  avatar?: T;
  socialPlatformLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}